C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS ROUTINE IS THE MAIN PROGRAM FOR MOLSCAT (ETC) VERSION 12 AND ONWARDS,
C  WITH DYNAMIC SPACE ALLOCATION CAPABILITY.
C
C  INCREASE MXDIM AS NECESSARY TO PROVIDE SUFFICIENT WORKSPACE.
C  IXNEXT,NIPR ARE INITIALIZED IN DRIVER
C
      USE memory, ONLY: MX,IXNEXT,NIPR,IDUMMY,X
      PARAMETER (MXDIM=1000000)
C     DOUBLE PRECISION X
C     DIMENSION X(MXDIM)
C     COMMON /MEMORY/ MX,IXNEXT,NIPR,IDUMMY,X
C
      MX=MXDIM
      allocate(X(MXDIM))

C
C  CALL PRINCIPAL MOLSCAT/BOUND/FIELD DRIVER SUBROUTINE
C
      CALL DRIVER
      STOP
      END
