      SUBROUTINE VRTP(IDERIV,R,V)
C  Copyright (C) 2025 A. Blech
      USE angles, ONLY: COSANG
      USE CO2_HE_V3_SELIM, ONLY : HECO2POTV3
C  THIS SUBROUTINE CALLS THE CO2-HE POTENTIAL FROM TAHA SELIM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE

      IF (IDERIV.NE.0) GOTO 100
      THETA=ACOS(COSANG(1))
      V=HECO2POTV3(R,COSANG(2),THETA)
C  NOTE THAT COSANG(2) IS Q FOR ITYP = 2
      RETURN
C
  100 IF (IDERIV.GT.0) THEN
        WRITE(6,601)
  601   FORMAT('  *** ERROR IN VRTP - POTENTIAL DERIVATIVES'//
     1         ' NOT SUPPORTED BY THIS VERSION')
        STOP
      ENDIF

      IF (IDERIV.LT.-1) RETURN

C  FOR IDERIV = -1 WE SET THE UNITS: RM=R, EPSIL=V
C  FOR THIS POTENTIAL, V IS RETURNED IN HARTREE AND R IS EXPECTED IN BOHR
      R=0.D0
      V=219474.63137098D0
      RETURN
      END
