      SUBROUTINE VRTP(IDERIV,R,V)
C  Copyright (C) 2025 A. Blech
      USE ANGLES, ONLY: COSANG
      USE CO2_HE_RIGID_GODARDPALLUET, ONLY : POTENTIEL
C  THIS SUBROUTINE CALLS THE CO2-HE POTENTIAL FROM AMELIE GODARD PALLUET
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE

      IF (IDERIV .EQ. 0) THEN
        THETA = ACOS(COSANG(1)) * (180D0 / ACOS(-1D0))
C  NOTE, THAT WE HAVE TO SUPPLY THETA IN DEGREES FOR THIS POTENTIAL
        CALL POTENTIEL(IDERIV,R,THETA,V)
        RETURN
      ELSEIF (IDERIV .GT. 0) THEN
        WRITE(6,601)
  601   FORMAT('  *** ERROR IN VRTP - POTENTIAL DERIVATIVES'//
     1         ' NOT SUPPORTED BY THIS VERSION')
        STOP
      ELSEIF (IDERIV .EQ. -1) THEN
C  FOR IDERIV = -1 WE SET THE UNITS: RM=R, EPSIL=V
C  FOR THIS POTENTIAL, V IS RETURNED IN CM-1 AND R IS EXPECTED IN BOHR
        CALL POTENTIEL(IDERIV,4.0D0,0.0D0,V)
        R=0.D0
        V=1.D0
        RETURN
      ELSE
C (IDERIV .LT. -1)
        WRITE(6,602) IDERIV
  602   FORMAT('  *** ERROR IN VRTP - IDERIV ', I4, 'UNSUPPORTED')
        STOP
      ENDIF

      END
