      SUBROUTINE VRTP(IDERIV,R,V)
C  Copyright (C) 2025 A. Blech
      USE angles, ONLY: COSANG
      USE CO2_HE_RIGID_GODARDPALLUET, ONLY : POTENTIEL
C  THIS SUBROUTINE CALLS THE CO2-HE POTENTIAL FROM AMELIE GODARD PALLUET
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE

      IF (IDERIV.NE.0) GOTO 100
      THETA = ACOS(COSANG(1)) * (180d0 / ACOS(-1d0))
C  NOTE, THAT WE HAVE TO SUPPLY THETA IN DEGREES FOR THIS POTENTIAL
      call POTENTIEL(IDERIV,R,THETA,V)
      RETURN
C
  100 IF (IDERIV.GT.0) THEN
        WRITE(6,601)
  601   FORMAT('  *** ERROR IN VRTP - POTENTIAL DERIVATIVES'//
     1         ' NOT SUPPORTED BY THIS VERSION')
        STOP
      ENDIF

      IF (IDERIV.LT.-1) RETURN

C  FOR IDERIV = -1 WE SET THE UNITS: RM=R, EPSIL=V
C  FOR THIS POTENTIAL, V IS RETURNED IN CM-1 AND R IS EXPECTED IN BOHR
      CALL POTENTIEL(IDERIV,4.0d0,0.0d0,V)
      R=0.D0
      V=1.D0
      RETURN
      END
